/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DeepSeekBalance, DeepSeekDelegatedSpend, DeepSeekSessionSpend, DeepSeekSessionTurnSpends, DeepSeekTodaySessionsSpend, DeepSeekTodaySpend, DeepSeekTurnSpend } from '@rayadesu/dsh-llm-billing/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$62696c6c696e67 {
    getBalance: (force?: boolean) => Promise<RemoteResult<DeepSeekBalance>>
    getDelegatedSpend: (sessionId: SessionId, force?: boolean) => Promise<RemoteResult<DeepSeekDelegatedSpend>>
    getSessionSpend: (sessionId: SessionId) => Promise<RemoteResult<DeepSeekSessionSpend>>
    getSessionTurnSpends: (sessionId: SessionId) => Promise<RemoteResult<DeepSeekSessionTurnSpends>>
    getTodaySessionsSpend: (force?: boolean) => Promise<RemoteResult<DeepSeekTodaySessionsSpend>>
    getTodaySpend: (force?: boolean) => Promise<RemoteResult<DeepSeekTodaySpend>>
    getTurnSpend: (sessionId: SessionId, messageId: string) => Promise<RemoteResult<DeepSeekTurnSpend>>
  }
  interface TypertRemoteMap {
    'billing/getBalance': (force?: boolean) => Promise<RemoteResult<DeepSeekBalance>>
    'billing/getDelegatedSpend': (sessionId: SessionId, force?: boolean) => Promise<RemoteResult<DeepSeekDelegatedSpend>>
    'billing/getSessionSpend': (sessionId: SessionId) => Promise<RemoteResult<DeepSeekSessionSpend>>
    'billing/getSessionTurnSpends': (sessionId: SessionId) => Promise<RemoteResult<DeepSeekSessionTurnSpends>>
    'billing/getTodaySessionsSpend': (force?: boolean) => Promise<RemoteResult<DeepSeekTodaySessionsSpend>>
    'billing/getTodaySpend': (force?: boolean) => Promise<RemoteResult<DeepSeekTodaySpend>>
    'billing/getTurnSpend': (sessionId: SessionId, messageId: string) => Promise<RemoteResult<DeepSeekTurnSpend>>
  }
  interface TypertRemoteNamespaceMap {
    'billing': TypertRemoteNamespace$62696c6c696e67
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
