/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _rayadesu_dsh_llm_billing_billing_getBalance_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getBalance_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getBalance_parameter_0$schema$value ??= z.union([z.undefined(), z.literal(false), z.literal(true)]))
let _rayadesu_dsh_llm_billing_billing_getBalance_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getBalance_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getBalance_result$schema$value ??= z.object({
  'isAvailable': z.boolean(),
  'lines': z.array(z.object({
  'currency': z.string(),
  'total': z.string(),
  'granted': z.string(),
  'toppedUp': z.string(),
})),
}))
let _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_1$schema$value
const _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_1$schema = () => (_rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_1$schema$value ??= z.union([z.undefined(), z.literal(false), z.literal(true)]))
let _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getDelegatedSpend_result$schema$value ??= z.object({
  'total': z.number(),
  'models': z.array(z.object({
  'model': z.string(),
  'displayName': z.string(),
  'cost': z.number(),
  'peakCost': z.number(),
  'offPeakCost': z.number(),
  'cacheHitInputTokens': z.number(),
  'cacheMissInputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheHitInputCost': z.number(),
  'cacheMissInputCost': z.number(),
  'outputCost': z.number(),
})),
  'isSubagent': z.boolean(),
  'crossedDay': z.boolean(),
}))
let _rayadesu_dsh_llm_billing_billing_getSessionSpend_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getSessionSpend_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getSessionSpend_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _rayadesu_dsh_llm_billing_billing_getSessionSpend_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getSessionSpend_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getSessionSpend_result$schema$value ??= z.object({
  'total': z.number(),
  'models': z.array(z.object({
  'model': z.string(),
  'displayName': z.string(),
  'cost': z.number(),
  'peakCost': z.number(),
  'offPeakCost': z.number(),
  'cacheHitInputTokens': z.number(),
  'cacheMissInputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheHitInputCost': z.number(),
  'cacheMissInputCost': z.number(),
  'outputCost': z.number(),
})),
  'unpriced': z.union([z.undefined(), z.object({
  'events': z.number(),
  'tokens': z.number(),
  'models': z.array(z.string()),
})]).optional(),
}))
let _rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_result$schema$value ??= z.object({
  'turns': z.array(z.object({
  'messageId': z.string(),
  'total': z.number(),
})),
}))
let _rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_parameter_0$schema$value ??= z.union([z.undefined(), z.literal(false), z.literal(true)]))
let _rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_result$schema$value ??= z.object({
  'sessions': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
  'title': z.union([z.literal(null), z.string()]),
  'total': z.number(),
  'ownTotal': z.number(),
})),
}))
let _rayadesu_dsh_llm_billing_billing_getTodaySpend_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getTodaySpend_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getTodaySpend_parameter_0$schema$value ??= z.union([z.undefined(), z.literal(false), z.literal(true)]))
let _rayadesu_dsh_llm_billing_billing_getTodaySpend_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getTodaySpend_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getTodaySpend_result$schema$value ??= z.object({
  'total': z.number(),
  'models': z.array(z.object({
  'model': z.string(),
  'displayName': z.string(),
  'cost': z.number(),
  'peakCost': z.number(),
  'offPeakCost': z.number(),
  'cacheHitInputTokens': z.number(),
  'cacheMissInputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheHitInputCost': z.number(),
  'cacheMissInputCost': z.number(),
  'outputCost': z.number(),
})),
  'unpriced': z.union([z.undefined(), z.object({
  'events': z.number(),
  'tokens': z.number(),
  'models': z.array(z.string()),
})]).optional(),
}))
let _rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_0$schema$value
const _rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_0$schema = () => (_rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_1$schema$value
const _rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_1$schema = () => (_rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_1$schema$value ??= z.string())
let _rayadesu_dsh_llm_billing_billing_getTurnSpend_result$schema$value
const _rayadesu_dsh_llm_billing_billing_getTurnSpend_result$schema = () => (_rayadesu_dsh_llm_billing_billing_getTurnSpend_result$schema$value ??= z.object({
  'total': z.number(),
}))

export const TYPERT = {
  package: '@rayadesu/dsh-llm-billing',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@rayadesu/dsh-llm-billing#billing/getBalance',
      service: 'billing',
      namespace: 'billing',
      method: 'getBalance',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getBalance:force',
            create: _rayadesu_dsh_llm_billing_billing_getBalance_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekBalance',
        create: _rayadesu_dsh_llm_billing_billing_getBalance_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":258,"column":3},
    },
    {
      id: '@rayadesu/dsh-llm-billing#billing/getDelegatedSpend',
      service: 'billing',
      namespace: 'billing',
      method: 'getDelegatedSpend',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getDelegatedSpend:sessionId',
            create: _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_0$schema,
          },
        },
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getDelegatedSpend:force',
            create: _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekDelegatedSpend',
        create: _rayadesu_dsh_llm_billing_billing_getDelegatedSpend_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":312,"column":3},
    },
    {
      id: '@rayadesu/dsh-llm-billing#billing/getSessionSpend',
      service: 'billing',
      namespace: 'billing',
      method: 'getSessionSpend',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getSessionSpend:sessionId',
            create: _rayadesu_dsh_llm_billing_billing_getSessionSpend_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekSessionSpend',
        create: _rayadesu_dsh_llm_billing_billing_getSessionSpend_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":269,"column":3},
    },
    {
      id: '@rayadesu/dsh-llm-billing#billing/getSessionTurnSpends',
      service: 'billing',
      namespace: 'billing',
      method: 'getSessionTurnSpends',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getSessionTurnSpends:sessionId',
            create: _rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekSessionTurnSpends',
        create: _rayadesu_dsh_llm_billing_billing_getSessionTurnSpends_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":337,"column":3},
    },
    {
      id: '@rayadesu/dsh-llm-billing#billing/getTodaySessionsSpend',
      service: 'billing',
      namespace: 'billing',
      method: 'getTodaySessionsSpend',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getTodaySessionsSpend:force',
            create: _rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekTodaySessionsSpend',
        create: _rayadesu_dsh_llm_billing_billing_getTodaySessionsSpend_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":297,"column":3},
    },
    {
      id: '@rayadesu/dsh-llm-billing#billing/getTodaySpend',
      service: 'billing',
      namespace: 'billing',
      method: 'getTodaySpend',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getTodaySpend:force',
            create: _rayadesu_dsh_llm_billing_billing_getTodaySpend_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekTodaySpend',
        create: _rayadesu_dsh_llm_billing_billing_getTodaySpend_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":282,"column":3},
    },
    {
      id: '@rayadesu/dsh-llm-billing#billing/getTurnSpend',
      service: 'billing',
      namespace: 'billing',
      method: 'getTurnSpend',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getTurnSpend:sessionId',
            create: _rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_0$schema,
          },
        },
        {
          name: 'messageId',
          wire: 'messageId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rayadesu/dsh-llm-billing#billing/getTurnSpend:messageId',
            create: _rayadesu_dsh_llm_billing_billing_getTurnSpend_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rayadesu/dsh-llm-billing/types#DeepSeekTurnSpend',
        create: _rayadesu_dsh_llm_billing_billing_getTurnSpend_result$schema,
      },
      sourceLocation: {"file":"packages/llm-billing/src/balance.ts","line":325,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
